name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install psycopg2-binary

      - name: Setup PostgreSQL
  # You may pin to the exact commit or the version.
  # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: credentials
    # POSTGRES_USER - create the specified user with superuser power
          postgresql user: postgres
    # POSTGRES_PASSWORD - superuser password
          postgresql password: Jtrip23@

      - name: Run Python script
        run: python script.py
